language: python

python:
  - "2.7"

env:
  - DJANGO=">=1.6,<1.7"
  - DJANGO=">=1.5,<1.6"
  - DJANGO=">=1.4,<1.5"
  - DJANGO=">=1.3,<1.4"

install:
  - pip install -q -r requirements.txt
  - pip install -q -r test-requirements.txt
  - pip install -q -I "Django $DJANGO"
  - pip install python-coveralls
  - python setup.py -q install

script: ./run-tests.sh

after_success: coveralls
